name: Kompilacja Flox przez MinGW

on:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    # 1. Pobieramy Twój kod z repozytorium
    - uses: actions/checkout@v4

    # 2. Rezygnujemy z ociężałego msys2 i instalujemy czyste, szybkie MinGW przez Chocolatey
    - name: Instalacja kompilatora MinGW (g++)
      run: |
        choco install mingw --strip-version -y
        echo "C:\tools\mingw64\bin" >> $GITHUB_PATH
      shell: pwsh

    # 3. Kompilujemy Flox w czystym PowerShellu z Twoimi atomowymi flagami
    - name: Kompilacja Flox z extreme performance
      run: |
        g++ -Ofast -flto flox.cpp -o flox.exe
      shell: pwsh

    # 4. Pakujemy gotowy plik 140 KB do pobrania
    - uses: actions/upload-artifact@v4
      with:
        name: flox-windows-mingw
        path: flox.exe
